#! /bin/sh
# /etc/init.d/raspberry-pipeline

export HOME
export RPI_HOME=/home/pi/raspberry-pipeline

case "$1" in
    start)
        echo "Starting raspberry-pipeline..."
        python $RPI_HOME/main.py 2>&1 &
    ;;
    stop)
        echo "Stopping raspberry-pipeline..."
        RPI_PID=`ps auxwww | grep main.py | grep -v grep | head -1 | awk '{print $2}'`
        if [ $RPI_PID ]
        then
          kill -9 $RPI_PID
        fi
        python $RPI_HOME/lights_off.py
    ;;
    *)
        echo "Usage: /etc/init.d/raspberry-pipeline {start|stop}"
        exit 1
    ;;
esac
exit 0